const placeHolder = {
  idMeal: '52948',
  strMeal: 'Food',
  strDrinkAlternate: null,
  strCategory: 'Pork',
  strArea: 'Chinese',
  strInstructions: '',
  strMealThumb: '',
  strTags: 'MainMeal',
  strYoutube: '',
  strIngredient1: 'ingredient',
  strIngredient2: 'ingredient',
  strIngredient3: '',
  strIngredient4: '',
  strIngredient5: '',
  strIngredient6: '',
  strIngredient7: '',
  strIngredient8: '',
  strIngredient9: '',
  strIngredient10: '',
  strIngredient11: '',
  strIngredient12: '',
  strIngredient13: '',
  strIngredient14: '',
  strIngredient15: '',
  strIngredient16: '',
  strIngredient17: '',
  strIngredient18: '',
  strIngredient19: '',
  strIngredient20: '',
  strMeasure1: '1 cup',
  strMeasure2: '1 cup',
  strMeasure3: '',
  strMeasure4: '',
  strMeasure5: '',
  strMeasure6: '',
  strMeasure7: '',
  strMeasure8: '',
  strMeasure9: '',
  strMeasure10: '',
  strMeasure11: '',
  strMeasure12: '',
  strMeasure13: '',
  strMeasure14: '',
  strMeasure15: '',
  strMeasure16: '',
  strMeasure17: '',
  strMeasure18: '',
  strMeasure19: '',
  strMeasure20: '',
  strSource: 'http://www.geniuskitchen.com/recipe/chinese-wontons-20235',
  strImageSource: null,
  strCreativeCommonsConfirmed: null,
  dateModified: null,
};

export default placeHolder;
